# Generated by Django 5.2.8 on 2025-12-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roomapplication',
            name='department',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='guardian_email',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='guardian_name',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='guardian_phone',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='hall',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='session',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='special_requests',
        ),
        migrations.RemoveField(
            model_name='roomapplication',
            name='student_id',
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='allocated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='cgpa',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roomapplication',
            name='special_request',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='roomapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
