# Generated by Django 5.2.8 on 2025-11-15 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_alter_roomapplication_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomapplication',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='roomapplication',
            name='hall',
            field=models.CharField(choices=[('shamshen_naher', 'Shamshen Naher Hall'), ('sufia_kamal', 'Sufia Kamal Hall'), ('tapose_rabeya', 'Tapose Rabeya Hall')], max_length=50),
        ),
        migrations.AlterField(
            model_name='roomapplication',
            name='room_type',
            field=models.CharField(choices=[('Standard Room (4 People)', 'Standard Room (4 People)'), ('Gono Room (6 People)', 'Gono Room (6 People)')], max_length=50),
        ),
    ]
