# Generated by Django 5.2.8 on 2026-01-18 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0002_remove_roomapplication_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='student_id',
        ),
    ]
