# Generated by Django 5.2.8 on 2025-11-15 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allocation', '0003_roomapplication_room_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomapplication',
            name='year',
            field=models.CharField(choices=[('1', '1st Year'), ('2', '2nd Year'), ('3', '3rd Year'), ('4', '4th Year'), ('5', '5th Year')], max_length=1),
        ),
    ]
